execute pathogen#infect()

filetype plugin indent on
syntax on

" display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·
set nowrap       "Don't wrap lines
set wrap linebreak nolist

set encoding=utf-8
set autoindent " automatically set indent of new line
set smartindent
set number " show line numbers 
set hlsearch " highlight search results
set noswapfile " do not create swap file
set laststatus=2
set scrolloff=4

autocmd BufRead *.erb set filetype=ruby
autocmd Filetype ruby setlocal tabstop=2 shiftwidth=2
autocmd Filetype html setlocal tabstop=2 shiftwidth=2
autocmd Filetype css setlocal tabstop=2 shiftwidth=2
autocmd Filetype go setlocal tabstop=4 shiftwidth=4

" run golint when saving with :w
autocmd BufWritePost,FileWritePost *.go execute 'GoImports' | cwindow
autocmd BufWritePost,FileWritePost *.go execute 'GoLint' | cwindow

" make arrow keys useless, habit breaking
noremap <Up>    :echo "Ueeeeeepa!"<cr>
noremap <Down>  :echo "Ueeeeeepa!"<cr>
noremap <Left>  :echo "Ueeeeeepa!"<cr>
noremap <Right> :echo "Ueeeeeepa!"<cr>

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" column limit 80 chars
if exists('+colorcolumn')
  set colorcolumn=80
endif
